### ISSUE TITLE
RubyMine support

### ISSUE THREAD

**Issue by AlanFoster** [jinsihou19/ReactSnippets#4]
It's not currently possible to install this plugin via RubyMine, would be great to add support for it.
Currently the supported list appears to be:

> Compatible with: IntelliJ IDEA  PhpStorm  WebStorm  PyCharm  GoLand  Android Studio
> - https://plugins.jetbrains.com/plugin/10113-react-snippets

Oddly I can directly install the plugin via the relases jar though

**Comment by jinsihou19** [comment]
List of supported products has been updated. Supported RubyMine now.
