### ISSUE TITLE
React 16.8.3 support

### ISSUE THREAD

**Issue by arkadiusm** [jinsihou19/ReactSnippets#5]
Hi, Are you planning to add support for React 16.8.3 life cycle?

**Comment by karlkras** [comment]
So is this project pretty much dead? It's a great start, but there can be much more added here.
@jinsihou19 , looks like there's been little done here for > 2 years. Is there another like plugin that's taken its place?

**Comment by DustinRobison** [comment]
@jinsihou19 , I could make make a PR for React 16.8.3 support but are you still around to merge it?

**Comment by jinsihou19** [comment]
> @jinsihou19 , I could make make a PR for React 16.8.3 support but are you still around to merge it?

sure

**Comment by jinsihou19** [comment]
Supported hooks now.
